services:
  postgres_backend:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: password
  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP Server
