services:
  postgres_backend:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: password
  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - "8025:8025"  # Web UI
      - "1025:1025"  # SMTP Server

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        sleep 5 &&
        mc alias set local http://minio:9000 admin password &&
        mc mb local/fmv || true
      "
