spring:
  application:
    name: backend
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/postgres
    username: backend
    password: password

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: backend
    password: password

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

app:
  jwt:
    issuer: "snapiter"
    access-ttl-minutes: 15
    refresh-ttl-days: 30
    secret: "${JWT_SECRET:c-vm3KMpNiyaLmnDvZsDrgIPpr8OW_tO0zUI0R3kJGE}" # Change it on production!
  email:
    ttl-minutes: 15
    frontend-email-url: "${FRONTEND_EMAIL_URL:http://localhost:3000/dashboard/auth/consume}"
    from: "${FROM_EMAIL:noreply@snapiter.com}"


aws:
  s3:
    bucket: ${BUCKET:fmv}
    region: ${AWS_REGION:eu-central-1}
    endpoint: ${AWS_END_POINT:http://127.0.0.1:9000}
    access-key-id: ${AWS_ACCESS_KEY:admin}
    secret-access-key: ${AWS_SECRET_KEY:password}
    force-path-style: ${AWS_FORCE_PATH_STYLE:true}
    files-dir: "markers/"