spring:
  application:
    name: backend
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:5432/postgres
    username: backend
    password: password

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: backend
    password: password

  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

app:
  jwt:
    issuer: "snapiter"
    access-ttl-minutes: 15
    refresh-ttl-days: 30
    secret: "${JWT_SECRET:c-vm3KMpNiyaLmnDvZsDrgIPpr8OW_tO0zUI0R3kJGE}" # Change it on production!
  email:
    ttl-minutes: 15
    frontend-email-url: "${FRONTEND_EMAIL_URL:http://localhost:3000/email}"
    from: "${FROM_EMAIL:noreply@snapiter.com}"
