name: Build and publish snapiter

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Gradle wrapper is executable (just in case)
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: ./gradlew clean test

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish :latest with Gradle (main branch)
        if: github.ref == 'refs/heads/main'
        run: |
          ./gradlew bootBuildImage \
            --imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            --publishImage

      - name: Build & Publish tag with Gradle (on git tag like v1.2.3)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF_NAME}
          ./gradlew bootBuildImage \
            --imageName=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${TAG} \
            --publishImage
